version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0
    restart: always
    ports:
      # Желательно чтобы клиентский и серверный порты отличались
      - "8000:8000"

  nginx:
    image: nginx:1.25-alpine3.17-slim
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always